### ISSUE TITLE
[FIX] 습관 방 시작한 당일부터 인증 가능하도록 데이터 처리 수정

### ISSUE THREAD

**Issue by youngkwon02** [TeamSparker/Spark-Server#197]
## 📌  Issue
- 습관 방 시작한 당일에는 습관 인증이 불가능 했음

## 📝  To-do
- [x] 당일 인증이 가능하도록 start 및 end date 조정
- [x] start API 호출 시 생성되는 record의 day 값 수정
- [x] roomDetailGET API 호출 시 day 계산 방법 수정
