### ISSUE TITLE
[FEAT] 푸시알림 그룹화 및 이미지 패싱

### ISSUE THREAD

**Issue by youngkwon02** [TeamSparker/Spark-Server#215]
## 📝  To-do
- [x] FCM 메시지 포멧 수정
- [x] 푸시알림 그룹화 및 인증사진 이미지 전송 기존 코드에 적용하기
- [x] alarmMessage constant에 category 추가
