### ISSUE TITLE
[FEAT] 습관방 상세 조회 API Update

### ISSUE THREAD

**Issue by youngkwon02** [TeamSparker/Spark-Server#449]
## 📝  To-do
- [x] 습관방 상세 조회 API에 Life Timeline 빨콩 정보 추가
- [x] 습관방 상세 조회 API에 isTermNew 응답 값 추가
- [x] 습관방 상세 조회 API 호출 시, entry.new_term False로 전환
- [x] 생명 충전 시, entry.new_term True로 전환
