### ISSUE TITLE
[FEAT] 매일 24시 스케줄링 이벤트 추가

### ISSUE THREAD

**Issue by xxeol2** [TeamSparker/Spark-Server#64]
## 📌  Issue

-  매일 24시 스케줄링 이벤트 추가

## 📝  To-do

- [x] 인증완료 인원수 check 후 생명 감소
- [x] 생명 0이 되면 방 폭파
- [x] record column 생성
